#!/usr/bin/env python
"""Regenerate the committed contract fixtures under ``contracts/fixtures/``.

    python scripts/gen_contract_fixtures.py                # rewrite the suite
    python scripts/gen_contract_fixtures.py --check        # fail if it is stale (CI)
    python scripts/gen_contract_fixtures.py --republish X  # rewrite a RELEASED version

**A released version is frozen, and this script enforces that.**
``contracts/fixtures/published.json`` records the sha256 of every file as it was
released. If regenerating would change a file under a version listed there, this
script REFUSES and names the version to bump. That refusal is the whole point:
every other check in this repo compares the fixtures to what the code produces
today, so before it existed a developer could rename a column, run this script,
and ship — with `jobs.v2` still stamped on a tab that no consumer's reader can
find a column in. Four codebases, zero rows each, no error anywhere.

So the order is always: **bump the version first, regenerate second.**

``--republish <version>`` exists only for fixing a genuine typo in a released
fixture, needs a CHANGELOG line naming that version, and rewrites bytes a
consumer may already have pinned. It is not a way to land a contract change.

The fixtures are generated by calling the exporter's own grid builders on the
synthetic records in ``tests/st_exporter/fixtures/contract_cases.py`` — the same
functions ``run.py`` calls, so a fixture can never pin a code path the exporter
does not actually use.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "src"))

from st_exporter import contracts  # noqa: E402  (sys.path is set up just above)
from tests.st_exporter.fixtures.contract_cases import (  # noqa: E402
    SOURCE_RECORDS,
)

#: Keys whose value is rendered one ELEMENT per line rather than exploded over
#: four lines apiece. Plain JSON either way — this only makes a fixture diff show
#: "row 3 changed" instead of thirty moved lines, which is what someone reviewing
#: a contract change actually needs to see.
_COMPACT_ELEMENT_KEYS = ("columns", "row_key", "rows")


def render(payload: dict) -> str:
    """One canonical serialisation, so a regeneration is a no-op when nothing changed."""
    placeholders = {}
    shell_payload = dict(payload)
    for key in _COMPACT_ELEMENT_KEYS:
        if not isinstance(payload.get(key), list):
            continue
        placeholder = f"__{key.upper()}__"
        placeholders[placeholder] = _compact_list(payload[key], indent=4)
        shell_payload[key] = placeholder
    text = json.dumps(shell_payload, indent=2, ensure_ascii=False, sort_keys=False)
    for placeholder, rendered in placeholders.items():
        text = text.replace(f'"{placeholder}"', rendered)
    return text + "\n"


def _compact_list(values: list, *, indent: int) -> str:
    if not values:
        return "[]"
    pad = " " * indent
    body = ",\n".join(pad + json.dumps(value, ensure_ascii=False) for value in values)
    return "[\n" + body + "\n" + " " * (indent - 2) + "]"


def build_files() -> dict[str, str]:
    """Repo-relative path -> file contents, for the whole suite including the manifest."""
    files: dict[str, str] = {}
    feeds: dict[str, dict] = {}

    for contract in contracts.FEEDS:
        tabs: dict[str, dict] = {}
        for tab in contract.tabs:
            grid = tab.build(SOURCE_RECORDS[tab.name])
            relative = contracts.fixture_relative_path(contract, tab)
            text = render(contracts.fixture_payload(contract, tab, grid))
            files[f"{contracts.FIXTURE_ROOT}/{relative}"] = text
            tabs[tab.name] = {
                "path": relative,
                "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                "row_count": len(grid) - 1,
            }
        feeds[contract.feed] = {"contract_version": contract.version, "tabs": tabs}

    manifest = {
        "docs": "docs/export-contract.md",
        "generated_by": "scripts/gen_contract_fixtures.py",
        "contains_real_customer_data": False,
        "feeds": feeds,
    }
    files[contracts.MANIFEST_PATH] = render(manifest)
    return files


# --- the published register ---------------------------------------------------
#
# Everything above this line describes what the code produces NOW. The register
# is the only thing in the suite that remembers what was actually RELEASED, and
# so the only thing that can tell a version bump from a quiet rewrite.


class MissingRegisterError(RuntimeError):
    """The register is gone and version directories exist — refuse, do not rebuild."""


def load_register() -> dict[str, dict[str, str]]:
    """version directory -> {file name: sha256 as released}.

    A MISSING register is an error, not an empty one, whenever any version
    directory already exists. Rebuilding it from whatever the code produces today
    would hand back the exact bypass this file exists to close: delete the
    register, regenerate, and every released version is silently re-baselined to
    the renamed column. Only a suite with no version directories at all — a fresh
    checkout of a repo that has never generated one — bootstraps.
    """
    path = REPO_ROOT / contracts.PUBLISHED_PATH
    if path.exists():
        document = json.loads(path.read_text(encoding="utf-8"))
        versions: dict[str, dict[str, str]] = document["versions"]
        return versions
    root = REPO_ROOT / contracts.FIXTURE_ROOT
    existing = sorted(p.name for p in root.glob("*") if p.is_dir()) if root.exists() else []
    if existing:
        raise MissingRegisterError(
            f"{contracts.PUBLISHED_PATH} IS MISSING, but {existing} are already "
            f"published.\nIt is the only record of the bytes each version was released "
            f"with; regenerating it from today's code would re-baseline every one of "
            f"them silently.\nRestore it: git checkout {contracts.PUBLISHED_PATH}"
        )
    return {}


def render_register(versions: dict[str, dict[str, str]]) -> str:
    document = {
        "_what_this_is": (
            "sha256 of every contract fixture AS RELEASED, per contract version. A file "
            "under a version listed here may never change: bump the version instead. "
            "Written by scripts/gen_contract_fixtures.py; asserted by "
            "tests/st_exporter/test_contract_fixtures.py."
        ),
        "versions": {
            version: dict(sorted(files.items())) for version, files in sorted(versions.items())
        },
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _changelog_mentions_republishing(version: str) -> bool:
    """A republish rewrites bytes a consumer may already have pinned, so it has to
    leave a trace somewhere a consumer will read."""
    changelog = REPO_ROOT / "CHANGELOG.md"
    if not changelog.exists():
        return False
    for line in changelog.read_text(encoding="utf-8").splitlines():
        lowered = line.lower()
        if version.lower() in lowered and "republish" in lowered:
            return True
    return False


def frozen_violations(
    files: dict[str, str], register: dict[str, dict[str, str]]
) -> dict[str, list[str]]:
    """Version -> the files under it whose bytes would change. Empty is the good case."""
    violations: dict[str, list[str]] = {}
    for relative, text in sorted(files.items()):
        version = contracts.version_of_fixture(relative)
        if version is None:
            continue  # the manifest and the register are not versioned
        released = register.get(version)
        if released is None:
            continue  # a brand-new version: nothing has been published under it yet
        name = relative.rsplit("/", 1)[-1]
        recorded = released.get(name)
        if recorded is not None and recorded == _digest(text):
            continue
        violations.setdefault(version, []).append(name)
    return violations


def _refuse(violations: dict[str, list[str]], republish: str | None) -> str:
    lines = ["REFUSING TO REWRITE A PUBLISHED CONTRACT VERSION.", ""]
    for version, names in sorted(violations.items()):
        lines.append(f"  {contracts.published_bump_hint(version)}")
        for name in names:
            lines.append(f"      {version}/{name} would change")
    lines += [
        "",
        "These bytes were RELEASED. TradeRated, TrueQuote and Profit Wizard each",
        "keep their own reader and test themselves against exactly these files, so",
        "changing them in place ships a different tab under a version stamp that",
        "says nothing changed — every consumer's version check passes and every",
        "consumer reads the old column name and gets ZERO ROWS.",
        "",
        "Do this instead:",
        "  1. bump the feed's contract version in src/st_exporter/contracts.py",
        "     (or the module it reads the version from);",
        f"  2. re-run {contracts.REGENERATE_COMMAND} — the new version directory is",
        "     written and the old one is left exactly as it was published;",
        "  3. tell TradeRated, TrueQuote and Profit Wizard to widen their range.",
        "",
        "If instead this is a genuine TYPO in a released fixture, add a CHANGELOG",
        "line naming the version and the word 'republish', then re-run with",
        f"  {contracts.REGENERATE_COMMAND} {contracts.REPUBLISH_FLAG} <version>",
    ]
    if republish:
        lines += [
            "",
            f"({contracts.REPUBLISH_FLAG} {republish} was passed but does not cover the "
            "versions above, or CHANGELOG.md has no line naming it alongside 'republish'.)",
        ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if the committed suite is stale",
    )
    parser.add_argument(
        "--republish",
        metavar="VERSION",
        help=(
            "rewrite an ALREADY PUBLISHED contract version (e.g. jobs.v2) in place. "
            "For fixing a typo in a released fixture, never for a contract change; "
            "requires a CHANGELOG.md line naming the version and 'republish'."
        ),
    )
    args = parser.parse_args()

    files = build_files()
    try:
        register = load_register()
    except MissingRegisterError as exc:
        print(exc)
        return 2

    violations = frozen_violations(files, register)
    if args.republish and _changelog_mentions_republishing(args.republish):
        violations.pop(args.republish, None)
    if violations:
        print(_refuse(violations, args.republish))
        return 2

    for relative, text in sorted(files.items()):
        version = contracts.version_of_fixture(relative)
        if version is None:
            continue
        register.setdefault(version, {})[relative.rsplit("/", 1)[-1]] = _digest(text)
    files[contracts.PUBLISHED_PATH] = render_register(register)

    stale: list[str] = []
    for relative, text in sorted(files.items()):
        path = REPO_ROOT / relative
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(relative)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")

    if args.check:
        if stale:
            print("Contract fixtures are STALE:\n  " + "\n  ".join(stale))
            print(
                "\nIf a COLUMN, GRAIN or ROW KEY changed, BUMP the feed's contract "
                "version first; then regenerate: " + contracts.REGENERATE_COMMAND
            )
            return 1
        print("Contract fixtures are up to date.")
        return 0

    if stale:
        print("Rewrote:\n  " + "\n  ".join(stale))
        print(
            "\nIf any COLUMN, GRAIN or ROW KEY changed, the feed's contract "
            "version must ALREADY have been bumped (this script refuses to "
            "rewrite a published one), and TradeRated / TrueQuote / Profit "
            "Wizard told. See docs/export-contract.md."
        )
    else:
        print("Contract fixtures already up to date — nothing written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
