#!/usr/bin/env python
"""Regenerate the committed contract fixtures under ``contracts/fixtures/``.

    python scripts/gen_contract_fixtures.py                # rewrite the suite
    python scripts/gen_contract_fixtures.py --check        # fail if it is stale (CI)
    python scripts/gen_contract_fixtures.py --republish X  # rewrite a RELEASED version

**A released version is frozen, and this script enforces that.**
``contracts/fixtures/published.json`` records the sha256 of every file as it was
released. If regenerating would change a file under a version listed there, this
script REFUSES and names the version to bump. That refusal is the whole point:
every other check in this repo compares the fixtures to what the code produces
today, so before it existed a developer could rename a column, run this script,
and ship — with `jobs.v2` still stamped on a tab that no consumer's reader can
find a column in. Four codebases, zero rows each, no error anywhere.

So the order is always: **bump the version first, regenerate second.**

``--republish <version>`` exists only for fixing a genuine typo in a released
fixture, needs a CHANGELOG line naming that version, and rewrites bytes a
consumer may already have pinned. It is not a way to land a contract change, and
that is enforced STRUCTURALLY, not by the CHANGELOG line: a republish may change
cell TEXT only. If `columns`, `row_key`, `grain`, the set of tabs or the number
of rows would move, it is refused however the CHANGELOG is worded. The CHANGELOG
line stays as the audit trail a consumer can find; it was never a gate, because
free text a hurried developer copies out of a refusal message cannot tell a
transposed digit from a renamed column.

Three things are refusals rather than "nothing to do", because each one was a
way through:

- a file REGISTERED under a version the code still produces, that the code no
  longer produces. Removing a tab used to regenerate cleanly at the same version
  — the manifest quietly dropped the tab while the fixture and its register entry
  stayed on disk, so a consumer's tests kept passing against a tab the exporter
  had stopped writing. ADDING a tab to a released version was already refused;
  removing one has to be too.
- a version DIRECTORY on disk with no entry in the register. Deleting one
  version's key re-baselined exactly that version on the next run, which is the
  "delete the whole register" bypass one level down.
- the register file missing entirely while any version directory exists.

The fixtures are generated by calling the exporter's own grid builders on the
synthetic records in ``tests/st_exporter/fixtures/contract_cases.py`` — the same
functions ``run.py`` calls, so a fixture can never pin a code path the exporter
does not actually use.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "src"))

from st_exporter import contracts  # noqa: E402  (sys.path is set up just above)
from tests.st_exporter.fixtures.contract_cases import (  # noqa: E402
    SOURCE_RECORDS,
)

#: Keys whose value is rendered one ELEMENT per line rather than exploded over
#: four lines apiece. Plain JSON either way — this only makes a fixture diff show
#: "row 3 changed" instead of thirty moved lines, which is what someone reviewing
#: a contract change actually needs to see.
_COMPACT_ELEMENT_KEYS = ("columns", "row_key", "rows")


def render(payload: dict) -> str:
    """One canonical serialisation, so a regeneration is a no-op when nothing changed."""
    placeholders = {}
    shell_payload = dict(payload)
    for key in _COMPACT_ELEMENT_KEYS:
        if not isinstance(payload.get(key), list):
            continue
        placeholder = f"__{key.upper()}__"
        placeholders[placeholder] = _compact_list(payload[key], indent=4)
        shell_payload[key] = placeholder
    text = json.dumps(shell_payload, indent=2, ensure_ascii=False, sort_keys=False)
    for placeholder, rendered in placeholders.items():
        text = text.replace(f'"{placeholder}"', rendered)
    return text + "\n"


def _compact_list(values: list, *, indent: int) -> str:
    if not values:
        return "[]"
    pad = " " * indent
    body = ",\n".join(pad + json.dumps(value, ensure_ascii=False) for value in values)
    return "[\n" + body + "\n" + " " * (indent - 2) + "]"


def build_files() -> dict[str, str]:
    """Repo-relative path -> file contents, for the whole suite including the manifest."""
    files: dict[str, str] = {}
    feeds: dict[str, dict] = {}

    for contract in contracts.FEEDS:
        tabs: dict[str, dict] = {}
        for tab in contract.tabs:
            grid = tab.build(SOURCE_RECORDS[tab.name])
            relative = contracts.fixture_relative_path(contract, tab)
            text = render(contracts.fixture_payload(contract, tab, grid))
            files[f"{contracts.FIXTURE_ROOT}/{relative}"] = text
            tabs[tab.name] = {
                "path": relative,
                "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                "row_count": len(grid) - 1,
            }
        feeds[contract.feed] = {"contract_version": contract.version, "tabs": tabs}

    manifest = {
        "docs": "docs/export-contract.md",
        "generated_by": "scripts/gen_contract_fixtures.py",
        "contains_real_customer_data": False,
        "feeds": feeds,
    }
    files[contracts.MANIFEST_PATH] = render(manifest)
    return files


# --- the published register ---------------------------------------------------
#
# Everything above this line describes what the code produces NOW. The register
# is the only thing in the suite that remembers what was actually RELEASED, and
# so the only thing that can tell a version bump from a quiet rewrite.


class MissingRegisterError(RuntimeError):
    """The register is gone and version directories exist — refuse, do not rebuild."""


class UnregisteredVersionError(RuntimeError):
    """A version directory exists on disk that the register does not list.

    Same bypass as a missing register, one level down: the register is a JSON
    object, so deleting ONE version's key costs a two-line edit and used to be
    read as "brand new, nothing published under it yet". The next run then
    re-baselined that version to whatever the code produces today — a renamed
    column included — and every check went green with the old version stamp still
    on the tab. A directory already on disk is by definition not brand new.
    """


def version_directories() -> list[str]:
    """Every contract-version directory that already exists under the fixture root."""
    root = REPO_ROOT / contracts.FIXTURE_ROOT
    if not root.exists():
        return []
    return sorted(p.name for p in root.glob("*") if p.is_dir() and not p.name.startswith("."))


def load_register() -> dict[str, dict[str, str]]:
    """version directory -> {file name: sha256 as released}.

    A MISSING register is an error, not an empty one, whenever any version
    directory already exists. Rebuilding it from whatever the code produces today
    would hand back the exact bypass this file exists to close: delete the
    register, regenerate, and every released version is silently re-baselined to
    the renamed column. Only a suite with no version directories at all — a fresh
    checkout of a repo that has never generated one — bootstraps.
    """
    path = REPO_ROOT / contracts.PUBLISHED_PATH
    if path.exists():
        document = json.loads(path.read_text(encoding="utf-8"))
        versions: dict[str, dict[str, str]] = document["versions"]
        unregistered = [name for name in version_directories() if name not in versions]
        if unregistered:
            raise UnregisteredVersionError(
                f"{unregistered} ALREADY EXIST under {contracts.FIXTURE_ROOT}/ but are "
                f"not listed in {contracts.PUBLISHED_PATH}.\nA directory on disk is not a "
                f"brand-new version: treating it as one would re-baseline it to whatever "
                f"the code produces today, which is the whole bypass this register "
                f"closes — one deleted key instead of one deleted file.\nRestore the "
                f"entry: git checkout {contracts.PUBLISHED_PATH}"
            )
        return versions
    existing = version_directories()
    if existing:
        raise MissingRegisterError(
            f"{contracts.PUBLISHED_PATH} IS MISSING, but {existing} are already "
            f"published.\nIt is the only record of the bytes each version was released "
            f"with; regenerating it from today's code would re-baseline every one of "
            f"them silently.\nRestore it: git checkout {contracts.PUBLISHED_PATH}"
        )
    return {}


def render_register(versions: dict[str, dict[str, str]]) -> str:
    document = {
        "_what_this_is": (
            "sha256 of every contract fixture AS RELEASED, per contract version. A file "
            "under a version listed here may never change: bump the version instead. "
            "Written by scripts/gen_contract_fixtures.py; asserted by "
            "tests/st_exporter/test_contract_fixtures.py."
        ),
        "versions": {
            version: dict(sorted(files.items())) for version, files in sorted(versions.items())
        },
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _changelog_mentions_republishing(version: str) -> bool:
    """A republish rewrites bytes a consumer may already have pinned, so it has to
    leave a trace somewhere a consumer will read."""
    changelog = REPO_ROOT / "CHANGELOG.md"
    if not changelog.exists():
        return False
    for line in changelog.read_text(encoding="utf-8").splitlines():
        lowered = line.lower()
        if version.lower() in lowered and "republish" in lowered:
            return True
    return False


def produced_by_version(files: dict[str, str]) -> dict[str, dict[str, str]]:
    """version -> {file name: text}, for the versioned half of what the code produces."""
    produced: dict[str, dict[str, str]] = {}
    for relative, text in files.items():
        version = contracts.version_of_fixture(relative)
        if version is None:
            continue  # the manifest and the register are not versioned
        produced.setdefault(version, {})[relative.rsplit("/", 1)[-1]] = text
    return produced


#: What a republish may NEVER move. Everything a consumer's reader keys on lives
#: here: the header row it looks columns up in, the tuple it keys its own store
#: on, the sentence saying what one row IS, and how many rows there are. A typo
#: fix changes CELL TEXT and nothing else.
_REPUBLISH_FROZEN_KEYS = ("columns", "row_key", "grain")


def republish_refusals(version: str, files: dict[str, str]) -> list[str]:
    """Why ``--republish <version>`` is not a typo fix. Empty means it is one.

    The CHANGELOG line never constrained anything: it is free text, and the
    refusal message this script prints hands the developer the exact wording to
    paste. So the flag is gated on STRUCTURE instead — the released file on disk
    is parsed, the new payload is parsed, and only the text inside cells is
    allowed to differ. A renamed column, a re-ordered header, a changed grain, a
    changed row_key, a row appearing or disappearing, a tab appearing or
    disappearing: each is a contract change wearing a typo's clothes, and each is
    refused here whatever the CHANGELOG says.
    """
    produced = produced_by_version(files).get(version, {})
    on_disk = REPO_ROOT / contracts.FIXTURE_ROOT / version
    released_names = sorted(p.name for p in on_disk.glob("*.json")) if on_disk.is_dir() else []

    refusals: list[str] = []
    for name in sorted(set(released_names) ^ set(produced)):
        side = "is no longer produced" if name in released_names else "is NEW"
        refusals.append(f"{version}/{name} {side} — a republish may not add or remove a tab")

    for name in sorted(set(released_names) & set(produced)):
        try:
            was = json.loads((on_disk / name).read_text(encoding="utf-8"))
            now = json.loads(produced[name])
        except (json.JSONDecodeError, OSError) as exc:
            refusals.append(f"{version}/{name} could not be compared as JSON: {exc}")
            continue
        for key in _REPUBLISH_FROZEN_KEYS:
            if was.get(key) != now.get(key):
                refusals.append(
                    f"{version}/{name}: '{key}' would change from {was.get(key)!r} to "
                    f"{now.get(key)!r}"
                )
        was_rows, now_rows = was.get("rows") or [], now.get("rows") or []
        if len(was_rows) != len(now_rows):
            refusals.append(
                f"{version}/{name}: the row COUNT would change from {len(was_rows)} to "
                f"{len(now_rows)}"
            )
    return refusals


def _refuse_republish(version: str, refusals: list[str]) -> str:
    return "\n".join(
        [
            f"REFUSING TO REPUBLISH {version} — THIS IS NOT A TYPO FIX.",
            "",
            *(f"      {line}" for line in refusals),
            "",
            f"{contracts.REPUBLISH_FLAG} rewrites bytes a consumer may already have",
            "pinned, so it may change CELL TEXT only: a transposed digit in a fake",
            "phone number, a misspelt fixture name. Columns, row_key, grain, the set",
            "of tabs and the number of rows are what every consumer's reader keys on,",
            "and moving any of them is a BREAKING contract change however it is",
            "described in the CHANGELOG.",
            "",
            f"  {contracts.published_bump_hint(version)} in src/st_exporter/contracts.py",
            f"  (or the module it reads the version from), then {contracts.REGENERATE_COMMAND}",
            "  — the new version directory is written and this one is left alone.",
        ]
    )


def frozen_violations(
    files: dict[str, str], register: dict[str, dict[str, str]]
) -> dict[str, list[str]]:
    """Version -> what would change under it, as lines. Empty is the good case.

    Two kinds of change, and the second one used to be invisible:

    1. a file whose BYTES would differ from the released ones (a renamed column,
       a changed cell, a row that moved) — including a file the code produces
       that the register never recorded, i.e. a tab ADDED to a released version;
    2. a file the register recorded that the code NO LONGER PRODUCES. Removing a
       tab regenerated cleanly at the same version: the manifest dropped it, the
       fixture and its register entry stayed on disk untouched, so the byte
       identity test still passed and a consumer kept testing itself against a
       tab the exporter had stopped writing. Zero rows, no error, the same
       version stamp. Only checked for versions the code still claims to write —
       a retired version (its feed has since bumped) legitimately produces
       nothing, and its directory stays forever by design.
    """
    violations: dict[str, list[str]] = {}
    produced = produced_by_version(files)

    for version, produced_files in sorted(produced.items()):
        released = register.get(version)
        if released is None:
            continue  # a brand-new version: nothing has been published under it yet
        for name, text in sorted(produced_files.items()):
            recorded = released.get(name)
            if recorded is not None and recorded == _digest(text):
                continue
            violations.setdefault(version, []).append(f"{version}/{name} would change")

    live_versions = set(contracts.CONTRACT_VERSIONS.values())
    for version, released in sorted(register.items()):
        if version not in live_versions:
            continue
        for name in sorted(set(released) - set(produced.get(version, {}))):
            violations.setdefault(version, []).append(
                f"{version}/{name} is REGISTERED as released but the code no longer "
                f"produces it — a tab was REMOVED from a version consumers still read"
            )
    return violations


def _refuse(violations: dict[str, list[str]], republish: str | None) -> str:
    lines = ["REFUSING TO REWRITE A PUBLISHED CONTRACT VERSION.", ""]
    for version, details in sorted(violations.items()):
        lines.append(f"  {contracts.published_bump_hint(version)}")
        for detail in details:
            lines.append(f"      {detail}")
    lines += [
        "",
        "These bytes were RELEASED. TradeRated, TrueQuote and Profit Wizard each",
        "keep their own reader and test themselves against exactly these files, so",
        "changing them in place ships a different tab under a version stamp that",
        "says nothing changed — every consumer's version check passes and every",
        "consumer reads the old column name and gets ZERO ROWS.",
        "",
        "Do this instead:",
        "  1. bump the feed's contract version in src/st_exporter/contracts.py",
        "     (or the module it reads the version from);",
        f"  2. re-run {contracts.REGENERATE_COMMAND} — the new version directory is",
        "     written and the old one is left exactly as it was published;",
        "  3. tell TradeRated, TrueQuote and Profit Wizard to widen their range.",
        "",
        "If instead this is a genuine TYPO in a released fixture, add a CHANGELOG",
        "line naming the version and the word 'republish', then re-run with",
        f"  {contracts.REGENERATE_COMMAND} {contracts.REPUBLISH_FLAG} <version>",
    ]
    if republish:
        lines += [
            "",
            f"({contracts.REPUBLISH_FLAG} {republish} was passed but does not cover the "
            "versions above, or CHANGELOG.md has no line naming it alongside 'republish'.)",
        ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if the committed suite is stale",
    )
    parser.add_argument(
        "--republish",
        metavar="VERSION",
        help=(
            "rewrite an ALREADY PUBLISHED contract version (e.g. jobs.v2) in place. "
            "For fixing a typo in a released fixture, never for a contract change; "
            "requires a CHANGELOG.md line naming the version and 'republish'."
        ),
    )
    args = parser.parse_args()

    files = build_files()
    try:
        register = load_register()
    except (MissingRegisterError, UnregisteredVersionError) as exc:
        print(exc)
        return 2

    violations = frozen_violations(files, register)
    if args.republish and args.republish in violations:
        # Two gates, and the structural one is the load-bearing one: the CHANGELOG
        # line is an audit trail, not a constraint.
        refusals = republish_refusals(args.republish, files)
        if refusals:
            print(_refuse_republish(args.republish, refusals))
            return 2
        if _changelog_mentions_republishing(args.republish):
            violations.pop(args.republish, None)
    if violations:
        print(_refuse(violations, args.republish))
        return 2

    for relative, text in sorted(files.items()):
        version = contracts.version_of_fixture(relative)
        if version is None:
            continue
        register.setdefault(version, {})[relative.rsplit("/", 1)[-1]] = _digest(text)
    files[contracts.PUBLISHED_PATH] = render_register(register)

    stale: list[str] = []
    for relative, text in sorted(files.items()):
        path = REPO_ROOT / relative
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(relative)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")

    if args.check:
        if stale:
            print("Contract fixtures are STALE:\n  " + "\n  ".join(stale))
            print(
                "\nIf a COLUMN, GRAIN or ROW KEY changed, BUMP the feed's contract "
                "version first; then regenerate: " + contracts.REGENERATE_COMMAND
            )
            return 1
        print("Contract fixtures are up to date.")
        return 0

    if stale:
        print("Rewrote:\n  " + "\n  ".join(stale))
        print(
            "\nIf any COLUMN, GRAIN or ROW KEY changed, the feed's contract "
            "version must ALREADY have been bumped (this script refuses to "
            "rewrite a published one), and TradeRated / TrueQuote / Profit "
            "Wizard told. See docs/export-contract.md."
        )
    else:
        print("Contract fixtures already up to date — nothing written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
