#!/usr/bin/env python
"""Regenerate the committed contract fixtures under ``contracts/fixtures/``.

    python scripts/gen_contract_fixtures.py          # rewrite the suite
    python scripts/gen_contract_fixtures.py --check  # fail if it is stale (CI)

Run this ONLY as a deliberate act, after a contract change you meant to make and
after bumping the affected feed's version in ``src/st_exporter/contracts.py`` (or
the module it reads the version from). Running it to make a red test go green is
the one way to defeat the guard: it rewrites the very thing four other codebases
check themselves against.

The fixtures are generated by calling the exporter's own grid builders on the
synthetic records in ``tests/st_exporter/fixtures/contract_cases.py`` — the same
functions ``run.py`` calls, so a fixture can never pin a code path the exporter
does not actually use.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "src"))

from st_exporter import contracts  # noqa: E402  (sys.path is set up just above)
from tests.st_exporter.fixtures.contract_cases import (  # noqa: E402
    SOURCE_RECORDS,
)

#: Keys whose value is rendered one ELEMENT per line rather than exploded over
#: four lines apiece. Plain JSON either way — this only makes a fixture diff show
#: "row 3 changed" instead of thirty moved lines, which is what someone reviewing
#: a contract change actually needs to see.
_COMPACT_ELEMENT_KEYS = ("columns", "row_key", "rows")


def render(payload: dict) -> str:
    """One canonical serialisation, so a regeneration is a no-op when nothing changed."""
    placeholders = {}
    shell_payload = dict(payload)
    for key in _COMPACT_ELEMENT_KEYS:
        if not isinstance(payload.get(key), list):
            continue
        placeholder = f"__{key.upper()}__"
        placeholders[placeholder] = _compact_list(payload[key], indent=4)
        shell_payload[key] = placeholder
    text = json.dumps(shell_payload, indent=2, ensure_ascii=False, sort_keys=False)
    for placeholder, rendered in placeholders.items():
        text = text.replace(f'"{placeholder}"', rendered)
    return text + "\n"


def _compact_list(values: list, *, indent: int) -> str:
    if not values:
        return "[]"
    pad = " " * indent
    body = ",\n".join(pad + json.dumps(value, ensure_ascii=False) for value in values)
    return "[\n" + body + "\n" + " " * (indent - 2) + "]"


def build_files() -> dict[str, str]:
    """Repo-relative path -> file contents, for the whole suite including the manifest."""
    files: dict[str, str] = {}
    feeds: dict[str, dict] = {}

    for contract in contracts.FEEDS:
        tabs: dict[str, dict] = {}
        for tab in contract.tabs:
            grid = tab.build(SOURCE_RECORDS[tab.name])
            relative = contracts.fixture_relative_path(contract, tab)
            text = render(contracts.fixture_payload(contract, tab, grid))
            files[f"{contracts.FIXTURE_ROOT}/{relative}"] = text
            tabs[tab.name] = {
                "path": relative,
                "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                "row_count": len(grid) - 1,
            }
        feeds[contract.feed] = {"contract_version": contract.version, "tabs": tabs}

    manifest = {
        "docs": "docs/export-contract.md",
        "generated_by": "scripts/gen_contract_fixtures.py",
        "contains_real_customer_data": False,
        "feeds": feeds,
    }
    files[contracts.MANIFEST_PATH] = render(manifest)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if the committed suite is stale",
    )
    args = parser.parse_args()

    files = build_files()
    stale: list[str] = []
    for relative, text in sorted(files.items()):
        path = REPO_ROOT / relative
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(relative)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")

    if args.check:
        if stale:
            print("Contract fixtures are STALE:\n  " + "\n  ".join(stale))
            print(f"\nRegenerate deliberately with: {contracts.REGENERATE_COMMAND}")
            return 1
        print("Contract fixtures are up to date.")
        return 0

    if stale:
        print("Rewrote:\n  " + "\n  ".join(stale))
        print(
            "\nIf any COLUMN, GRAIN or ROW KEY changed, the feed's contract "
            "version must be bumped too, and TradeRated / TrueQuote / Profit "
            "Wizard told. See docs/export-contract.md."
        )
    else:
        print("Contract fixtures already up to date — nothing written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
